export const projectsContent = {
  heading: "selected work",

  linkLabels: { demo: "live site", github: "source" } as Record<string, string>,

  items: [
    {
      slug: "corporate-platform-pt-wijaya-laksmi-bhuana-agung",
      title: "Corporate Platform — PT. Wijaya Laksmi Bhuana Agung",
      status: "Completed",
      year: "2026",
      role: "Full Stack",
      blurb: "Developed integrated corporate management and employee workspace platform.",
      tech: ["Next.js", "Laravel", "MySQL"],
      screens: ["/projects/wlb3.webp", "/projects/wlb1.webp", "/projects/wlb2.webp"],
      links: [],
    },
    {
      slug: "custom-erp-cv-dejavanese-autoparts",
      title: "Custom ERP — CV. Dejavanese Autoparts",
      status: "Completed",
      year: "2026",
      role: "Full Stack",
      blurb: "Developed ERP system for inventory, sales, and supply chain management.",
      tech: ["Laravel", "MySQL", "Tailwind"],
      screens: ["/projects/djv1.webp", "/projects/djv2.webp", "/projects/djv3.webp"],
      links: [],
    },
    {
      slug: "custom-erp-pprq-annasimiyyah",
      title: "Custom ERP — PPRQ Annasimiyyah",
      status: "Completed",
      year: "2025",
      role: "Full Stack",
      blurb: "ERP covering academics, syahriah payments, and permissions. Multi-role portal with official website and downloadable brochure.",
      tech: ["Next.js", "Laravel", "MySQL"],
      screens: ["/projects/sipprq1.webp", "/projects/sipprq2.webp", "/projects/sipprq3.webp"],
      links: [{ kind: "demo", href: "https://pprqportal.com/" }],
    },
    {
      slug: "laz-majt-web-system",
      title: "LAZ MAJT Web System",
      status: "Completed",
      year: "2025",
      role: "Full Stack",
      blurb: "ERP for zakat, infaq, and donation management with public donation portal, zakat calculator, static CMS, and official website.",
      tech: ["Laravel", "Tailwind", "MySQL"],
      screens: ["/projects/laz-1.webp", "/projects/laz-2.webp"],
      links: [{ kind: "demo", href: "https://majt.or.id/" }],
    },
    {
      slug: "custom-erp-aruna-cipta-perkasa",
      title: "Custom ERP — Aruna Cipta Perkasa",
      status: "Completed",
      year: "2025",
      role: "Full Stack",
      blurb: "Highly customized ERP with 9 user roles, full N8N workflow automation, and AI integration. Includes the company's official website.",
      tech: ["Next.js", "Laravel", "n8n", "AI"],
      screens: ["/projects/arcade1.webp", "/projects/arcade2.webp", "/projects/arcade3.webp"],
      links: [{ kind: "demo", href: "https://arcipta.com/" }],
    },
    {
      slug: "email-blasting-system-emtekdigital",
      title: "Email Blasting System — EmtekDigital",
      status: "Completed",
      year: "2025",
      role: "Backend",
      blurb: "Scalable Node.js email automation tool with scheduling, open rate tracking, and audience segmentation for an EO agency.",
      tech: ["Node.js", "Express", "API"],
      screens: ["/projects/email1.webp", "/projects/email2.webp", "/projects/email3.webp"],
      links: [],
    },
    {
      slug: "odoo-module-contractor-management",
      title: "Odoo Module Contractor Management",
      status: "Concept",
      year: "2025",
      role: "Odoo Developer",
      blurb: "An Odoo module for contractor management, designed to streamline project workflows and enhance operational efficiency.",
      tech: ["Odoo", "Python", "XML"],
      screens: ["/projects/odoo1.webp", "/projects/odoo2.webp", "/projects/odoo3.webp"],
      links: [{ kind: "github", href: "https://github.com/sakhandaru/odoo-dev" }],
    },
    {
      slug: "landing-page-tvku",
      title: "Landing Page TVKU",
      status: "Concept",
      year: "2025",
      role: "Front-end",
      blurb: "A modern, responsive landing page for TVKU, built with Next.js to ensure fast performance and SEO. Designed for a seamless user experience, focusing on modern design and accessibility.",
      tech: ["Next.js", "Framer Motion"],
      screens: ["/projects/tvku1.webp", "/projects/tvku2.webp", "/projects/tvku3.webp", "/projects/tvku4.webp"],
      links: [],
    },
    {
      slug: "chatbot-ai-assistant",
      title: "Chatbot AI Assistant",
      status: "Concept",
      year: "2025",
      role: "AI Developer",
      blurb: "An intelligent AI chatbot for the TVKU platform, designed to boost user engagement with real-time, personalized support. Leverages modern AI and NLP to create an intuitive, user-centric experience.",
      tech: ["React", "AI", "NLP", "Ollama"],
      screens: ["/projects/ai1.webp"],
      links: [],
    },
  ],
};

export type Project = (typeof projectsContent.items)[number];
