export const techstackContent = {
  label: "tech-stack",
  schema: "public",
  query:
    "SELECT table_name FROM information_schema.tables WHERE table_schema = 'public';",

  items: [
    { name: "JavaScript", icon: "/techstack/javascript.svg", category: "language" },
    { name: "TypeScript", icon: "/techstack/typescript.svg", category: "language" },
    { name: "PHP", icon: "/techstack/php.svg", category: "language" },
    { name: "Python", icon: "/techstack/python.svg", category: "language" },
    { name: "React", icon: "/techstack/react.svg", category: "framework" },
    { name: "Next.js", icon: "/techstack/nextjs.svg", category: "framework" },
    { name: "Laravel", icon: "/techstack/laravel.svg", category: "framework" },
    { name: "Node.js", icon: "/techstack/nodejs.svg", category: "framework" },
    { name: "Flask", icon: "/techstack/flask.svg", category: "framework" },
    { name: "MySQL", icon: "/techstack/mysql.svg", category: "database" },
    { name: "PostgreSQL", icon: "/techstack/postgresql.svg", category: "database" },
    { name: "MariaDB", icon: "/techstack/mariadb.svg", category: "database" },
    { name: "n8n", icon: "/techstack/n8n.svg", category: "tool" },
    { name: "Docker", icon: "/techstack/docker.svg", category: "tool" },
    // { name: "Podman", icon: "/techstack/Podman.svg", category: "tool" },
    { name: "Kubernetes", icon: "/techstack/Kubernetes.svg", category: "tool" },
    { name: "Linux", icon: "/techstack/linux.svg", category: "tool" },
    { name: "Git", icon: "/techstack/git.svg", category: "tool" },
    { name: "Figma", icon: "/techstack/figma.svg", category: "design" },
    { name: "pen.dev", icon: "/techstack/pendev.png", category: "design", raw: true },
    { name: "Notion", icon: "/techstack/notion.svg", category: "productivity" },
    { name: "Obsidian", icon: "/techstack/obsidian.svg", category: "productivity" },
  ],
} as const;
